spring.application.name=Spa
server.port = 8080

spring.datasource.url=jdbc:postgresql://localhost:5432/Barbearia
spring.datasource.username=postgres
spring.datasource.password= R@que0112
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update
